spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/checkmate
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  session:
    store-type: jdbc
    jdbc.initialize-schema: always
    timeout: 1h

  security:
    rememberme:
      key: ${REMEMBER_ME_KEY}

cloud:
  aws:
    s3:
      bucket: deepcheck-image-storage
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

# FastApi 모델 서버 기본 URL
model.server.url: http://localhost:8000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    org.springframework.security.authentication: debug
    org.springframework.security.web.authentication: debug
