spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/checkmate
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  security:
    rememberme:
      key: ${REMEMBER_ME_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    org.springframework.security.authentication: debug
    org.springframework.security.web.authentication: debug
